/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 05bee9de2fd2ff593f773acf524bf856)
interface __BaseEnv_Env {
	HOSTS: KVNamespace;
	ROUTER_KEY: SecretsStoreSecret;
	AUTH_RATE_LIMIT: RateLimit;
	GUEST_RATE_LIMIT: RateLimit;
	INTERVIEW_RATE_LIMIT: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
