/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as KitRouteImport } from './routes/kit'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellSplatRouteImport } from './routes/_shell.$'
import { Route as ShellActivityRouteImport } from './routes/_shell.activity'
import { Route as ShellConnectionsRouteImport } from './routes/_shell.connections'
import { Route as ShellMembersRouteImport } from './routes/_shell.members'
import { Route as ShellModelsRouteImport } from './routes/_shell.models'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as DecisionsDecisionRouteImport } from './routes/decisions.$decision'
import { Route as ShellAppsIndexRouteImport } from './routes/_shell.apps.index'
import { Route as ShellAppsAppRouteImport } from './routes/_shell.apps.$app'
import { Route as ShellIntegrationsIndexRouteImport } from './routes/_shell.integrations.index'
import { Route as ShellIntegrationsIntegrationRouteImport } from './routes/_shell.integrations.$integration'
import { Route as ShellKnowledgeIndexRouteImport } from './routes/_shell.knowledge.index'
import { Route as ShellKnowledgeCollectionRouteImport } from './routes/_shell.knowledge.$collection'
import { Route as ShellWorkflowsIndexRouteImport } from './routes/_shell.workflows.index'
import { Route as ShellWorkflowsAppWorkflowRouteImport } from './routes/_shell.workflows.$app.$workflow'
import { Route as AppsAppScreensScreenRouteImport } from './routes/apps.$app.screens.$screen'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSplatRoute = ShellSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ShellRoute,
} as any)
const ShellActivityRoute = ShellActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConnectionsRoute = ShellConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembersRoute = ShellMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModelsRoute = ShellModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const DecisionsDecisionRoute = DecisionsDecisionRouteImport.update({
  id: '/decisions/$decision',
  path: '/decisions/$decision',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAppsIndexRoute = ShellAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppsAppRoute = ShellAppsAppRouteImport.update({
  id: '/apps/$app',
  path: '/apps/$app',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsIndexRoute = ShellIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsIntegrationRoute =
  ShellIntegrationsIntegrationRouteImport.update({
    id: '/integrations/$integration',
    path: '/integrations/$integration',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellKnowledgeIndexRoute = ShellKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKnowledgeCollectionRoute =
  ShellKnowledgeCollectionRouteImport.update({
    id: '/knowledge/$collection',
    path: '/knowledge/$collection',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellWorkflowsIndexRoute = ShellWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkflowsAppWorkflowRoute =
  ShellWorkflowsAppWorkflowRouteImport.update({
    id: '/workflows/$app/$workflow',
    path: '/workflows/$app/$workflow',
    getParentRoute: () => ShellRoute,
  } as any)
const AppsAppScreensScreenRoute = AppsAppScreensScreenRouteImport.update({
  id: '/apps/$app/screens/$screen',
  path: '/apps/$app/screens/$screen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/guest': typeof GuestRoute
  '/kit': typeof KitRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof ShellSplatRoute
  '/activity': typeof ShellActivityRoute
  '/connections': typeof ShellConnectionsRoute
  '/members': typeof ShellMembersRoute
  '/models': typeof ShellModelsRoute
  '/notifications': typeof ShellNotificationsRoute
  '/decisions/$decision': typeof DecisionsDecisionRoute
  '/apps/$app': typeof ShellAppsAppRoute
  '/integrations/$integration': typeof ShellIntegrationsIntegrationRoute
  '/knowledge/$collection': typeof ShellKnowledgeCollectionRoute
  '/apps/': typeof ShellAppsIndexRoute
  '/integrations/': typeof ShellIntegrationsIndexRoute
  '/knowledge/': typeof ShellKnowledgeIndexRoute
  '/workflows/': typeof ShellWorkflowsIndexRoute
  '/workflows/$app/$workflow': typeof ShellWorkflowsAppWorkflowRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
}
export interface FileRoutesByTo {
  '/guest': typeof GuestRoute
  '/kit': typeof KitRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof ShellSplatRoute
  '/activity': typeof ShellActivityRoute
  '/connections': typeof ShellConnectionsRoute
  '/members': typeof ShellMembersRoute
  '/models': typeof ShellModelsRoute
  '/notifications': typeof ShellNotificationsRoute
  '/decisions/$decision': typeof DecisionsDecisionRoute
  '/': typeof ShellIndexRoute
  '/apps/$app': typeof ShellAppsAppRoute
  '/integrations/$integration': typeof ShellIntegrationsIntegrationRoute
  '/knowledge/$collection': typeof ShellKnowledgeCollectionRoute
  '/apps': typeof ShellAppsIndexRoute
  '/integrations': typeof ShellIntegrationsIndexRoute
  '/knowledge': typeof ShellKnowledgeIndexRoute
  '/workflows': typeof ShellWorkflowsIndexRoute
  '/workflows/$app/$workflow': typeof ShellWorkflowsAppWorkflowRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/guest': typeof GuestRoute
  '/kit': typeof KitRoute
  '/sign-in': typeof SignInRoute
  '/_shell/$': typeof ShellSplatRoute
  '/_shell/activity': typeof ShellActivityRoute
  '/_shell/connections': typeof ShellConnectionsRoute
  '/_shell/members': typeof ShellMembersRoute
  '/_shell/models': typeof ShellModelsRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/decisions/$decision': typeof DecisionsDecisionRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/apps/$app': typeof ShellAppsAppRoute
  '/_shell/integrations/$integration': typeof ShellIntegrationsIntegrationRoute
  '/_shell/knowledge/$collection': typeof ShellKnowledgeCollectionRoute
  '/_shell/apps/': typeof ShellAppsIndexRoute
  '/_shell/integrations/': typeof ShellIntegrationsIndexRoute
  '/_shell/knowledge/': typeof ShellKnowledgeIndexRoute
  '/_shell/workflows/': typeof ShellWorkflowsIndexRoute
  '/_shell/workflows/$app/$workflow': typeof ShellWorkflowsAppWorkflowRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guest'
    | '/kit'
    | '/sign-in'
    | '/$'
    | '/activity'
    | '/connections'
    | '/members'
    | '/models'
    | '/notifications'
    | '/decisions/$decision'
    | '/apps/$app'
    | '/integrations/$integration'
    | '/knowledge/$collection'
    | '/apps/'
    | '/integrations/'
    | '/knowledge/'
    | '/workflows/'
    | '/workflows/$app/$workflow'
    | '/apps/$app/screens/$screen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/guest'
    | '/kit'
    | '/sign-in'
    | '/$'
    | '/activity'
    | '/connections'
    | '/members'
    | '/models'
    | '/notifications'
    | '/decisions/$decision'
    | '/'
    | '/apps/$app'
    | '/integrations/$integration'
    | '/knowledge/$collection'
    | '/apps'
    | '/integrations'
    | '/knowledge'
    | '/workflows'
    | '/workflows/$app/$workflow'
    | '/apps/$app/screens/$screen'
  id:
    | '__root__'
    | '/_shell'
    | '/guest'
    | '/kit'
    | '/sign-in'
    | '/_shell/$'
    | '/_shell/activity'
    | '/_shell/connections'
    | '/_shell/members'
    | '/_shell/models'
    | '/_shell/notifications'
    | '/decisions/$decision'
    | '/_shell/'
    | '/_shell/apps/$app'
    | '/_shell/integrations/$integration'
    | '/_shell/knowledge/$collection'
    | '/_shell/apps/'
    | '/_shell/integrations/'
    | '/_shell/knowledge/'
    | '/_shell/workflows/'
    | '/_shell/workflows/$app/$workflow'
    | '/apps/$app/screens/$screen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  GuestRoute: typeof GuestRoute
  KitRoute: typeof KitRoute
  SignInRoute: typeof SignInRoute
  DecisionsDecisionRoute: typeof DecisionsDecisionRoute
  AppsAppScreensScreenRoute: typeof AppsAppScreensScreenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/$': {
      id: '/_shell/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof ShellSplatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/activity': {
      id: '/_shell/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ShellActivityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/connections': {
      id: '/_shell/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ShellConnectionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/members': {
      id: '/_shell/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof ShellMembersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/models': {
      id: '/_shell/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ShellModelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/decisions/$decision': {
      id: '/decisions/$decision'
      path: '/decisions/$decision'
      fullPath: '/decisions/$decision'
      preLoaderRoute: typeof DecisionsDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/apps/': {
      id: '/_shell/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof ShellAppsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/apps/$app': {
      id: '/_shell/apps/$app'
      path: '/apps/$app'
      fullPath: '/apps/$app'
      preLoaderRoute: typeof ShellAppsAppRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations/': {
      id: '/_shell/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof ShellIntegrationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations/$integration': {
      id: '/_shell/integrations/$integration'
      path: '/integrations/$integration'
      fullPath: '/integrations/$integration'
      preLoaderRoute: typeof ShellIntegrationsIntegrationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge/': {
      id: '/_shell/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof ShellKnowledgeIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge/$collection': {
      id: '/_shell/knowledge/$collection'
      path: '/knowledge/$collection'
      fullPath: '/knowledge/$collection'
      preLoaderRoute: typeof ShellKnowledgeCollectionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workflows/': {
      id: '/_shell/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof ShellWorkflowsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workflows/$app/$workflow': {
      id: '/_shell/workflows/$app/$workflow'
      path: '/workflows/$app/$workflow'
      fullPath: '/workflows/$app/$workflow'
      preLoaderRoute: typeof ShellWorkflowsAppWorkflowRouteImport
      parentRoute: typeof ShellRoute
    }
    '/apps/$app/screens/$screen': {
      id: '/apps/$app/screens/$screen'
      path: '/apps/$app/screens/$screen'
      fullPath: '/apps/$app/screens/$screen'
      preLoaderRoute: typeof AppsAppScreensScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellSplatRoute: typeof ShellSplatRoute
  ShellActivityRoute: typeof ShellActivityRoute
  ShellConnectionsRoute: typeof ShellConnectionsRoute
  ShellMembersRoute: typeof ShellMembersRoute
  ShellModelsRoute: typeof ShellModelsRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAppsAppRoute: typeof ShellAppsAppRoute
  ShellIntegrationsIntegrationRoute: typeof ShellIntegrationsIntegrationRoute
  ShellKnowledgeCollectionRoute: typeof ShellKnowledgeCollectionRoute
  ShellAppsIndexRoute: typeof ShellAppsIndexRoute
  ShellIntegrationsIndexRoute: typeof ShellIntegrationsIndexRoute
  ShellKnowledgeIndexRoute: typeof ShellKnowledgeIndexRoute
  ShellWorkflowsIndexRoute: typeof ShellWorkflowsIndexRoute
  ShellWorkflowsAppWorkflowRoute: typeof ShellWorkflowsAppWorkflowRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSplatRoute: ShellSplatRoute,
  ShellActivityRoute: ShellActivityRoute,
  ShellConnectionsRoute: ShellConnectionsRoute,
  ShellMembersRoute: ShellMembersRoute,
  ShellModelsRoute: ShellModelsRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellAppsAppRoute: ShellAppsAppRoute,
  ShellIntegrationsIntegrationRoute: ShellIntegrationsIntegrationRoute,
  ShellKnowledgeCollectionRoute: ShellKnowledgeCollectionRoute,
  ShellAppsIndexRoute: ShellAppsIndexRoute,
  ShellIntegrationsIndexRoute: ShellIntegrationsIndexRoute,
  ShellKnowledgeIndexRoute: ShellKnowledgeIndexRoute,
  ShellWorkflowsIndexRoute: ShellWorkflowsIndexRoute,
  ShellWorkflowsAppWorkflowRoute: ShellWorkflowsAppWorkflowRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  GuestRoute: GuestRoute,
  KitRoute: KitRoute,
  SignInRoute: SignInRoute,
  DecisionsDecisionRoute: DecisionsDecisionRoute,
  AppsAppScreensScreenRoute: AppsAppScreensScreenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
