/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as KitRouteImport } from './routes/kit'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellSplatRouteImport } from './routes/_shell.$'
import { Route as ShellActivityRouteImport } from './routes/_shell.activity'
import { Route as ShellConnectionsRouteImport } from './routes/_shell.connections'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellMembersRouteImport } from './routes/_shell.members'
import { Route as ShellModelsRouteImport } from './routes/_shell.models'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellOnboardingRouteImport } from './routes/_shell.onboarding'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as DecisionsDecisionRouteImport } from './routes/decisions.$decision'
import { Route as ShellAppsIndexRouteImport } from './routes/_shell.apps.index'
import { Route as ShellAppsAppRouteImport } from './routes/_shell.apps.$app'
import { Route as ShellDomainsIndexRouteImport } from './routes/_shell.domains.index'
import { Route as ShellEnginesIndexRouteImport } from './routes/_shell.engines.index'
import { Route as ShellIntegrationsIndexRouteImport } from './routes/_shell.integrations.index'
import { Route as ShellIntegrationsIntegrationRouteImport } from './routes/_shell.integrations.$integration'
import { Route as ShellKnowledgeIndexRouteImport } from './routes/_shell.knowledge.index'
import { Route as ShellKnowledgeCollectionRouteImport } from './routes/_shell.knowledge.$collection'
import { Route as ShellOnboardingIndexRouteImport } from './routes/_shell.onboarding.index'
import { Route as ShellOnboardingAgreementsRouteImport } from './routes/_shell.onboarding.agreements'
import { Route as ShellOnboardingKickoffRouteImport } from './routes/_shell.onboarding.kickoff'
import { Route as ShellOnboardingLogRouteImport } from './routes/_shell.onboarding.log'
import { Route as ShellOnboardingNotesRouteImport } from './routes/_shell.onboarding.notes'
import { Route as ShellOnboardingOpenRouteImport } from './routes/_shell.onboarding.open'
import { Route as ShellOnboardingStephenRouteImport } from './routes/_shell.onboarding.stephen'
import { Route as ShellSettingsIndexRouteImport } from './routes/_shell.settings.index'
import { Route as ShellSettingsApprovalsRouteImport } from './routes/_shell.settings.approvals'
import { Route as ShellSettingsAuditRouteImport } from './routes/_shell.settings.audit'
import { Route as ShellSettingsMembersRouteImport } from './routes/_shell.settings.members'
import { Route as ShellSettingsModelsRouteImport } from './routes/_shell.settings.models'
import { Route as ShellSettingsProfileRouteImport } from './routes/_shell.settings.profile'
import { Route as ShellSettingsSpendRouteImport } from './routes/_shell.settings.spend'
import { Route as ShellWorkflowsIndexRouteImport } from './routes/_shell.workflows.index'
import { Route as KitComponentsNameRouteImport } from './routes/kit_.components.$name'
import { Route as KitExamplesNameRouteImport } from './routes/kit_.examples.$name'
import { Route as ShellDomainsEngineIndexRouteImport } from './routes/_shell.domains.$engine.index'
import { Route as ShellEnginesEngineIndexRouteImport } from './routes/_shell.engines.$engine.index'
import { Route as ShellWorkflowsAppWorkflowRouteImport } from './routes/_shell.workflows.$app.$workflow'
import { Route as AppsAppScreensScreenRouteImport } from './routes/apps.$app.screens.$screen'
import { Route as ShellDomainsEngineAppsScreenRouteImport } from './routes/_shell.domains.$engine.apps.$screen'
import { Route as ShellEnginesEngineAppsScreenRouteImport } from './routes/_shell.engines.$engine.apps.$screen'
import { Route as DomainsEngineAppsScreenFullRouteImport } from './routes/domains.$engine.apps.$screen.full'
import { Route as EnginesEngineAppsScreenFullRouteImport } from './routes/engines.$engine.apps.$screen.full'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSplatRoute = ShellSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ShellRoute,
} as any)
const ShellActivityRoute = ShellActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConnectionsRoute = ShellConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembersRoute = ShellMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModelsRoute = ShellModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOnboardingRoute = ShellOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const DecisionsDecisionRoute = DecisionsDecisionRouteImport.update({
  id: '/decisions/$decision',
  path: '/decisions/$decision',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAppsIndexRoute = ShellAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppsAppRoute = ShellAppsAppRouteImport.update({
  id: '/apps/$app',
  path: '/apps/$app',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDomainsIndexRoute = ShellDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEnginesIndexRoute = ShellEnginesIndexRouteImport.update({
  id: '/engines/',
  path: '/engines/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsIndexRoute = ShellIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsIntegrationRoute =
  ShellIntegrationsIntegrationRouteImport.update({
    id: '/integrations/$integration',
    path: '/integrations/$integration',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellKnowledgeIndexRoute = ShellKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKnowledgeCollectionRoute =
  ShellKnowledgeCollectionRouteImport.update({
    id: '/knowledge/$collection',
    path: '/knowledge/$collection',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOnboardingIndexRoute = ShellOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellOnboardingRoute,
} as any)
const ShellOnboardingAgreementsRoute =
  ShellOnboardingAgreementsRouteImport.update({
    id: '/agreements',
    path: '/agreements',
    getParentRoute: () => ShellOnboardingRoute,
  } as any)
const ShellOnboardingKickoffRoute = ShellOnboardingKickoffRouteImport.update({
  id: '/kickoff',
  path: '/kickoff',
  getParentRoute: () => ShellOnboardingRoute,
} as any)
const ShellOnboardingLogRoute = ShellOnboardingLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => ShellOnboardingRoute,
} as any)
const ShellOnboardingNotesRoute = ShellOnboardingNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ShellOnboardingRoute,
} as any)
const ShellOnboardingOpenRoute = ShellOnboardingOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => ShellOnboardingRoute,
} as any)
const ShellOnboardingStephenRoute = ShellOnboardingStephenRouteImport.update({
  id: '/stephen',
  path: '/stephen',
  getParentRoute: () => ShellOnboardingRoute,
} as any)
const ShellSettingsIndexRoute = ShellSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsApprovalsRoute = ShellSettingsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsAuditRoute = ShellSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsMembersRoute = ShellSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsModelsRoute = ShellSettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsProfileRoute = ShellSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsSpendRoute = ShellSettingsSpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellWorkflowsIndexRoute = ShellWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => ShellRoute,
} as any)
const KitComponentsNameRoute = KitComponentsNameRouteImport.update({
  id: '/kit_/components/$name',
  path: '/kit/components/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const KitExamplesNameRoute = KitExamplesNameRouteImport.update({
  id: '/kit_/examples/$name',
  path: '/kit/examples/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDomainsEngineIndexRoute = ShellDomainsEngineIndexRouteImport.update({
  id: '/domains/$engine/',
  path: '/domains/$engine/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEnginesEngineIndexRoute = ShellEnginesEngineIndexRouteImport.update({
  id: '/engines/$engine/',
  path: '/engines/$engine/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkflowsAppWorkflowRoute =
  ShellWorkflowsAppWorkflowRouteImport.update({
    id: '/workflows/$app/$workflow',
    path: '/workflows/$app/$workflow',
    getParentRoute: () => ShellRoute,
  } as any)
const AppsAppScreensScreenRoute = AppsAppScreensScreenRouteImport.update({
  id: '/apps/$app/screens/$screen',
  path: '/apps/$app/screens/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDomainsEngineAppsScreenRoute =
  ShellDomainsEngineAppsScreenRouteImport.update({
    id: '/domains/$engine/apps/$screen',
    path: '/domains/$engine/apps/$screen',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellEnginesEngineAppsScreenRoute =
  ShellEnginesEngineAppsScreenRouteImport.update({
    id: '/engines/$engine/apps/$screen',
    path: '/engines/$engine/apps/$screen',
    getParentRoute: () => ShellRoute,
  } as any)
const DomainsEngineAppsScreenFullRoute =
  DomainsEngineAppsScreenFullRouteImport.update({
    id: '/domains/$engine/apps/$screen/full',
    path: '/domains/$engine/apps/$screen/full',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnginesEngineAppsScreenFullRoute =
  EnginesEngineAppsScreenFullRouteImport.update({
    id: '/engines/$engine/apps/$screen/full',
    path: '/engines/$engine/apps/$screen/full',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/guest': typeof GuestRoute
  '/kit': typeof KitRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof ShellSplatRoute
  '/activity': typeof ShellActivityRoute
  '/connections': typeof ShellConnectionsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/members': typeof ShellMembersRoute
  '/models': typeof ShellModelsRoute
  '/notifications': typeof ShellNotificationsRoute
  '/onboarding': typeof ShellOnboardingRouteWithChildren
  '/settings': typeof ShellSettingsRouteWithChildren
  '/decisions/$decision': typeof DecisionsDecisionRoute
  '/apps/$app': typeof ShellAppsAppRoute
  '/integrations/$integration': typeof ShellIntegrationsIntegrationRoute
  '/knowledge/$collection': typeof ShellKnowledgeCollectionRoute
  '/onboarding/agreements': typeof ShellOnboardingAgreementsRoute
  '/onboarding/kickoff': typeof ShellOnboardingKickoffRoute
  '/onboarding/log': typeof ShellOnboardingLogRoute
  '/onboarding/notes': typeof ShellOnboardingNotesRoute
  '/onboarding/open': typeof ShellOnboardingOpenRoute
  '/onboarding/stephen': typeof ShellOnboardingStephenRoute
  '/settings/approvals': typeof ShellSettingsApprovalsRoute
  '/settings/audit': typeof ShellSettingsAuditRoute
  '/settings/members': typeof ShellSettingsMembersRoute
  '/settings/models': typeof ShellSettingsModelsRoute
  '/settings/profile': typeof ShellSettingsProfileRoute
  '/settings/spend': typeof ShellSettingsSpendRoute
  '/kit/components/$name': typeof KitComponentsNameRoute
  '/kit/examples/$name': typeof KitExamplesNameRoute
  '/apps/': typeof ShellAppsIndexRoute
  '/domains/': typeof ShellDomainsIndexRoute
  '/engines/': typeof ShellEnginesIndexRoute
  '/integrations/': typeof ShellIntegrationsIndexRoute
  '/knowledge/': typeof ShellKnowledgeIndexRoute
  '/onboarding/': typeof ShellOnboardingIndexRoute
  '/settings/': typeof ShellSettingsIndexRoute
  '/workflows/': typeof ShellWorkflowsIndexRoute
  '/workflows/$app/$workflow': typeof ShellWorkflowsAppWorkflowRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
  '/domains/$engine/': typeof ShellDomainsEngineIndexRoute
  '/engines/$engine/': typeof ShellEnginesEngineIndexRoute
  '/domains/$engine/apps/$screen': typeof ShellDomainsEngineAppsScreenRoute
  '/engines/$engine/apps/$screen': typeof ShellEnginesEngineAppsScreenRoute
  '/domains/$engine/apps/$screen/full': typeof DomainsEngineAppsScreenFullRoute
  '/engines/$engine/apps/$screen/full': typeof EnginesEngineAppsScreenFullRoute
}
export interface FileRoutesByTo {
  '/guest': typeof GuestRoute
  '/kit': typeof KitRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof ShellSplatRoute
  '/activity': typeof ShellActivityRoute
  '/connections': typeof ShellConnectionsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/members': typeof ShellMembersRoute
  '/models': typeof ShellModelsRoute
  '/notifications': typeof ShellNotificationsRoute
  '/decisions/$decision': typeof DecisionsDecisionRoute
  '/': typeof ShellIndexRoute
  '/apps/$app': typeof ShellAppsAppRoute
  '/integrations/$integration': typeof ShellIntegrationsIntegrationRoute
  '/knowledge/$collection': typeof ShellKnowledgeCollectionRoute
  '/onboarding/agreements': typeof ShellOnboardingAgreementsRoute
  '/onboarding/kickoff': typeof ShellOnboardingKickoffRoute
  '/onboarding/log': typeof ShellOnboardingLogRoute
  '/onboarding/notes': typeof ShellOnboardingNotesRoute
  '/onboarding/open': typeof ShellOnboardingOpenRoute
  '/onboarding/stephen': typeof ShellOnboardingStephenRoute
  '/settings/approvals': typeof ShellSettingsApprovalsRoute
  '/settings/audit': typeof ShellSettingsAuditRoute
  '/settings/members': typeof ShellSettingsMembersRoute
  '/settings/models': typeof ShellSettingsModelsRoute
  '/settings/profile': typeof ShellSettingsProfileRoute
  '/settings/spend': typeof ShellSettingsSpendRoute
  '/kit/components/$name': typeof KitComponentsNameRoute
  '/kit/examples/$name': typeof KitExamplesNameRoute
  '/apps': typeof ShellAppsIndexRoute
  '/domains': typeof ShellDomainsIndexRoute
  '/engines': typeof ShellEnginesIndexRoute
  '/integrations': typeof ShellIntegrationsIndexRoute
  '/knowledge': typeof ShellKnowledgeIndexRoute
  '/onboarding': typeof ShellOnboardingIndexRoute
  '/settings': typeof ShellSettingsIndexRoute
  '/workflows': typeof ShellWorkflowsIndexRoute
  '/workflows/$app/$workflow': typeof ShellWorkflowsAppWorkflowRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
  '/domains/$engine': typeof ShellDomainsEngineIndexRoute
  '/engines/$engine': typeof ShellEnginesEngineIndexRoute
  '/domains/$engine/apps/$screen': typeof ShellDomainsEngineAppsScreenRoute
  '/engines/$engine/apps/$screen': typeof ShellEnginesEngineAppsScreenRoute
  '/domains/$engine/apps/$screen/full': typeof DomainsEngineAppsScreenFullRoute
  '/engines/$engine/apps/$screen/full': typeof EnginesEngineAppsScreenFullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/guest': typeof GuestRoute
  '/kit': typeof KitRoute
  '/sign-in': typeof SignInRoute
  '/_shell/$': typeof ShellSplatRoute
  '/_shell/activity': typeof ShellActivityRoute
  '/_shell/connections': typeof ShellConnectionsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/members': typeof ShellMembersRoute
  '/_shell/models': typeof ShellModelsRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/onboarding': typeof ShellOnboardingRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRouteWithChildren
  '/decisions/$decision': typeof DecisionsDecisionRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/apps/$app': typeof ShellAppsAppRoute
  '/_shell/integrations/$integration': typeof ShellIntegrationsIntegrationRoute
  '/_shell/knowledge/$collection': typeof ShellKnowledgeCollectionRoute
  '/_shell/onboarding/agreements': typeof ShellOnboardingAgreementsRoute
  '/_shell/onboarding/kickoff': typeof ShellOnboardingKickoffRoute
  '/_shell/onboarding/log': typeof ShellOnboardingLogRoute
  '/_shell/onboarding/notes': typeof ShellOnboardingNotesRoute
  '/_shell/onboarding/open': typeof ShellOnboardingOpenRoute
  '/_shell/onboarding/stephen': typeof ShellOnboardingStephenRoute
  '/_shell/settings/approvals': typeof ShellSettingsApprovalsRoute
  '/_shell/settings/audit': typeof ShellSettingsAuditRoute
  '/_shell/settings/members': typeof ShellSettingsMembersRoute
  '/_shell/settings/models': typeof ShellSettingsModelsRoute
  '/_shell/settings/profile': typeof ShellSettingsProfileRoute
  '/_shell/settings/spend': typeof ShellSettingsSpendRoute
  '/kit_/components/$name': typeof KitComponentsNameRoute
  '/kit_/examples/$name': typeof KitExamplesNameRoute
  '/_shell/apps/': typeof ShellAppsIndexRoute
  '/_shell/domains/': typeof ShellDomainsIndexRoute
  '/_shell/engines/': typeof ShellEnginesIndexRoute
  '/_shell/integrations/': typeof ShellIntegrationsIndexRoute
  '/_shell/knowledge/': typeof ShellKnowledgeIndexRoute
  '/_shell/onboarding/': typeof ShellOnboardingIndexRoute
  '/_shell/settings/': typeof ShellSettingsIndexRoute
  '/_shell/workflows/': typeof ShellWorkflowsIndexRoute
  '/_shell/workflows/$app/$workflow': typeof ShellWorkflowsAppWorkflowRoute
  '/apps/$app/screens/$screen': typeof AppsAppScreensScreenRoute
  '/_shell/domains/$engine/': typeof ShellDomainsEngineIndexRoute
  '/_shell/engines/$engine/': typeof ShellEnginesEngineIndexRoute
  '/_shell/domains/$engine/apps/$screen': typeof ShellDomainsEngineAppsScreenRoute
  '/_shell/engines/$engine/apps/$screen': typeof ShellEnginesEngineAppsScreenRoute
  '/domains/$engine/apps/$screen/full': typeof DomainsEngineAppsScreenFullRoute
  '/engines/$engine/apps/$screen/full': typeof EnginesEngineAppsScreenFullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guest'
    | '/kit'
    | '/sign-in'
    | '/$'
    | '/activity'
    | '/connections'
    | '/dashboard'
    | '/members'
    | '/models'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/decisions/$decision'
    | '/apps/$app'
    | '/integrations/$integration'
    | '/knowledge/$collection'
    | '/onboarding/agreements'
    | '/onboarding/kickoff'
    | '/onboarding/log'
    | '/onboarding/notes'
    | '/onboarding/open'
    | '/onboarding/stephen'
    | '/settings/approvals'
    | '/settings/audit'
    | '/settings/members'
    | '/settings/models'
    | '/settings/profile'
    | '/settings/spend'
    | '/kit/components/$name'
    | '/kit/examples/$name'
    | '/apps/'
    | '/domains/'
    | '/engines/'
    | '/integrations/'
    | '/knowledge/'
    | '/onboarding/'
    | '/settings/'
    | '/workflows/'
    | '/workflows/$app/$workflow'
    | '/apps/$app/screens/$screen'
    | '/domains/$engine/'
    | '/engines/$engine/'
    | '/domains/$engine/apps/$screen'
    | '/engines/$engine/apps/$screen'
    | '/domains/$engine/apps/$screen/full'
    | '/engines/$engine/apps/$screen/full'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/guest'
    | '/kit'
    | '/sign-in'
    | '/$'
    | '/activity'
    | '/connections'
    | '/dashboard'
    | '/members'
    | '/models'
    | '/notifications'
    | '/decisions/$decision'
    | '/'
    | '/apps/$app'
    | '/integrations/$integration'
    | '/knowledge/$collection'
    | '/onboarding/agreements'
    | '/onboarding/kickoff'
    | '/onboarding/log'
    | '/onboarding/notes'
    | '/onboarding/open'
    | '/onboarding/stephen'
    | '/settings/approvals'
    | '/settings/audit'
    | '/settings/members'
    | '/settings/models'
    | '/settings/profile'
    | '/settings/spend'
    | '/kit/components/$name'
    | '/kit/examples/$name'
    | '/apps'
    | '/domains'
    | '/engines'
    | '/integrations'
    | '/knowledge'
    | '/onboarding'
    | '/settings'
    | '/workflows'
    | '/workflows/$app/$workflow'
    | '/apps/$app/screens/$screen'
    | '/domains/$engine'
    | '/engines/$engine'
    | '/domains/$engine/apps/$screen'
    | '/engines/$engine/apps/$screen'
    | '/domains/$engine/apps/$screen/full'
    | '/engines/$engine/apps/$screen/full'
  id:
    | '__root__'
    | '/_shell'
    | '/guest'
    | '/kit'
    | '/sign-in'
    | '/_shell/$'
    | '/_shell/activity'
    | '/_shell/connections'
    | '/_shell/dashboard'
    | '/_shell/members'
    | '/_shell/models'
    | '/_shell/notifications'
    | '/_shell/onboarding'
    | '/_shell/settings'
    | '/decisions/$decision'
    | '/_shell/'
    | '/_shell/apps/$app'
    | '/_shell/integrations/$integration'
    | '/_shell/knowledge/$collection'
    | '/_shell/onboarding/agreements'
    | '/_shell/onboarding/kickoff'
    | '/_shell/onboarding/log'
    | '/_shell/onboarding/notes'
    | '/_shell/onboarding/open'
    | '/_shell/onboarding/stephen'
    | '/_shell/settings/approvals'
    | '/_shell/settings/audit'
    | '/_shell/settings/members'
    | '/_shell/settings/models'
    | '/_shell/settings/profile'
    | '/_shell/settings/spend'
    | '/kit_/components/$name'
    | '/kit_/examples/$name'
    | '/_shell/apps/'
    | '/_shell/domains/'
    | '/_shell/engines/'
    | '/_shell/integrations/'
    | '/_shell/knowledge/'
    | '/_shell/onboarding/'
    | '/_shell/settings/'
    | '/_shell/workflows/'
    | '/_shell/workflows/$app/$workflow'
    | '/apps/$app/screens/$screen'
    | '/_shell/domains/$engine/'
    | '/_shell/engines/$engine/'
    | '/_shell/domains/$engine/apps/$screen'
    | '/_shell/engines/$engine/apps/$screen'
    | '/domains/$engine/apps/$screen/full'
    | '/engines/$engine/apps/$screen/full'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  GuestRoute: typeof GuestRoute
  KitRoute: typeof KitRoute
  SignInRoute: typeof SignInRoute
  DecisionsDecisionRoute: typeof DecisionsDecisionRoute
  KitComponentsNameRoute: typeof KitComponentsNameRoute
  KitExamplesNameRoute: typeof KitExamplesNameRoute
  AppsAppScreensScreenRoute: typeof AppsAppScreensScreenRoute
  DomainsEngineAppsScreenFullRoute: typeof DomainsEngineAppsScreenFullRoute
  EnginesEngineAppsScreenFullRoute: typeof EnginesEngineAppsScreenFullRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/$': {
      id: '/_shell/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof ShellSplatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/activity': {
      id: '/_shell/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ShellActivityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/connections': {
      id: '/_shell/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ShellConnectionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/members': {
      id: '/_shell/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof ShellMembersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/models': {
      id: '/_shell/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ShellModelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/onboarding': {
      id: '/_shell/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ShellOnboardingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/decisions/$decision': {
      id: '/decisions/$decision'
      path: '/decisions/$decision'
      fullPath: '/decisions/$decision'
      preLoaderRoute: typeof DecisionsDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/apps/': {
      id: '/_shell/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof ShellAppsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/apps/$app': {
      id: '/_shell/apps/$app'
      path: '/apps/$app'
      fullPath: '/apps/$app'
      preLoaderRoute: typeof ShellAppsAppRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/domains/': {
      id: '/_shell/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof ShellDomainsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/engines/': {
      id: '/_shell/engines/'
      path: '/engines'
      fullPath: '/engines/'
      preLoaderRoute: typeof ShellEnginesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations/': {
      id: '/_shell/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof ShellIntegrationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations/$integration': {
      id: '/_shell/integrations/$integration'
      path: '/integrations/$integration'
      fullPath: '/integrations/$integration'
      preLoaderRoute: typeof ShellIntegrationsIntegrationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge/': {
      id: '/_shell/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof ShellKnowledgeIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge/$collection': {
      id: '/_shell/knowledge/$collection'
      path: '/knowledge/$collection'
      fullPath: '/knowledge/$collection'
      preLoaderRoute: typeof ShellKnowledgeCollectionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/onboarding/': {
      id: '/_shell/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof ShellOnboardingIndexRouteImport
      parentRoute: typeof ShellOnboardingRoute
    }
    '/_shell/onboarding/agreements': {
      id: '/_shell/onboarding/agreements'
      path: '/agreements'
      fullPath: '/onboarding/agreements'
      preLoaderRoute: typeof ShellOnboardingAgreementsRouteImport
      parentRoute: typeof ShellOnboardingRoute
    }
    '/_shell/onboarding/kickoff': {
      id: '/_shell/onboarding/kickoff'
      path: '/kickoff'
      fullPath: '/onboarding/kickoff'
      preLoaderRoute: typeof ShellOnboardingKickoffRouteImport
      parentRoute: typeof ShellOnboardingRoute
    }
    '/_shell/onboarding/log': {
      id: '/_shell/onboarding/log'
      path: '/log'
      fullPath: '/onboarding/log'
      preLoaderRoute: typeof ShellOnboardingLogRouteImport
      parentRoute: typeof ShellOnboardingRoute
    }
    '/_shell/onboarding/notes': {
      id: '/_shell/onboarding/notes'
      path: '/notes'
      fullPath: '/onboarding/notes'
      preLoaderRoute: typeof ShellOnboardingNotesRouteImport
      parentRoute: typeof ShellOnboardingRoute
    }
    '/_shell/onboarding/open': {
      id: '/_shell/onboarding/open'
      path: '/open'
      fullPath: '/onboarding/open'
      preLoaderRoute: typeof ShellOnboardingOpenRouteImport
      parentRoute: typeof ShellOnboardingRoute
    }
    '/_shell/onboarding/stephen': {
      id: '/_shell/onboarding/stephen'
      path: '/stephen'
      fullPath: '/onboarding/stephen'
      preLoaderRoute: typeof ShellOnboardingStephenRouteImport
      parentRoute: typeof ShellOnboardingRoute
    }
    '/_shell/settings/': {
      id: '/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ShellSettingsIndexRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/approvals': {
      id: '/_shell/settings/approvals'
      path: '/approvals'
      fullPath: '/settings/approvals'
      preLoaderRoute: typeof ShellSettingsApprovalsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/audit': {
      id: '/_shell/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof ShellSettingsAuditRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/members': {
      id: '/_shell/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof ShellSettingsMembersRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/models': {
      id: '/_shell/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof ShellSettingsModelsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/profile': {
      id: '/_shell/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ShellSettingsProfileRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/spend': {
      id: '/_shell/settings/spend'
      path: '/spend'
      fullPath: '/settings/spend'
      preLoaderRoute: typeof ShellSettingsSpendRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/workflows/': {
      id: '/_shell/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof ShellWorkflowsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/kit_/components/$name': {
      id: '/kit_/components/$name'
      path: '/kit/components/$name'
      fullPath: '/kit/components/$name'
      preLoaderRoute: typeof KitComponentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit_/examples/$name': {
      id: '/kit_/examples/$name'
      path: '/kit/examples/$name'
      fullPath: '/kit/examples/$name'
      preLoaderRoute: typeof KitExamplesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/domains/$engine/': {
      id: '/_shell/domains/$engine/'
      path: '/domains/$engine'
      fullPath: '/domains/$engine/'
      preLoaderRoute: typeof ShellDomainsEngineIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/engines/$engine/': {
      id: '/_shell/engines/$engine/'
      path: '/engines/$engine'
      fullPath: '/engines/$engine/'
      preLoaderRoute: typeof ShellEnginesEngineIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workflows/$app/$workflow': {
      id: '/_shell/workflows/$app/$workflow'
      path: '/workflows/$app/$workflow'
      fullPath: '/workflows/$app/$workflow'
      preLoaderRoute: typeof ShellWorkflowsAppWorkflowRouteImport
      parentRoute: typeof ShellRoute
    }
    '/apps/$app/screens/$screen': {
      id: '/apps/$app/screens/$screen'
      path: '/apps/$app/screens/$screen'
      fullPath: '/apps/$app/screens/$screen'
      preLoaderRoute: typeof AppsAppScreensScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/domains/$engine/apps/$screen': {
      id: '/_shell/domains/$engine/apps/$screen'
      path: '/domains/$engine/apps/$screen'
      fullPath: '/domains/$engine/apps/$screen'
      preLoaderRoute: typeof ShellDomainsEngineAppsScreenRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/engines/$engine/apps/$screen': {
      id: '/_shell/engines/$engine/apps/$screen'
      path: '/engines/$engine/apps/$screen'
      fullPath: '/engines/$engine/apps/$screen'
      preLoaderRoute: typeof ShellEnginesEngineAppsScreenRouteImport
      parentRoute: typeof ShellRoute
    }
    '/domains/$engine/apps/$screen/full': {
      id: '/domains/$engine/apps/$screen/full'
      path: '/domains/$engine/apps/$screen/full'
      fullPath: '/domains/$engine/apps/$screen/full'
      preLoaderRoute: typeof DomainsEngineAppsScreenFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines/$engine/apps/$screen/full': {
      id: '/engines/$engine/apps/$screen/full'
      path: '/engines/$engine/apps/$screen/full'
      fullPath: '/engines/$engine/apps/$screen/full'
      preLoaderRoute: typeof EnginesEngineAppsScreenFullRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellOnboardingRouteChildren {
  ShellOnboardingAgreementsRoute: typeof ShellOnboardingAgreementsRoute
  ShellOnboardingKickoffRoute: typeof ShellOnboardingKickoffRoute
  ShellOnboardingLogRoute: typeof ShellOnboardingLogRoute
  ShellOnboardingNotesRoute: typeof ShellOnboardingNotesRoute
  ShellOnboardingOpenRoute: typeof ShellOnboardingOpenRoute
  ShellOnboardingStephenRoute: typeof ShellOnboardingStephenRoute
  ShellOnboardingIndexRoute: typeof ShellOnboardingIndexRoute
}

const ShellOnboardingRouteChildren: ShellOnboardingRouteChildren = {
  ShellOnboardingAgreementsRoute: ShellOnboardingAgreementsRoute,
  ShellOnboardingKickoffRoute: ShellOnboardingKickoffRoute,
  ShellOnboardingLogRoute: ShellOnboardingLogRoute,
  ShellOnboardingNotesRoute: ShellOnboardingNotesRoute,
  ShellOnboardingOpenRoute: ShellOnboardingOpenRoute,
  ShellOnboardingStephenRoute: ShellOnboardingStephenRoute,
  ShellOnboardingIndexRoute: ShellOnboardingIndexRoute,
}

const ShellOnboardingRouteWithChildren = ShellOnboardingRoute._addFileChildren(
  ShellOnboardingRouteChildren,
)

interface ShellSettingsRouteChildren {
  ShellSettingsApprovalsRoute: typeof ShellSettingsApprovalsRoute
  ShellSettingsAuditRoute: typeof ShellSettingsAuditRoute
  ShellSettingsMembersRoute: typeof ShellSettingsMembersRoute
  ShellSettingsModelsRoute: typeof ShellSettingsModelsRoute
  ShellSettingsProfileRoute: typeof ShellSettingsProfileRoute
  ShellSettingsSpendRoute: typeof ShellSettingsSpendRoute
  ShellSettingsIndexRoute: typeof ShellSettingsIndexRoute
}

const ShellSettingsRouteChildren: ShellSettingsRouteChildren = {
  ShellSettingsApprovalsRoute: ShellSettingsApprovalsRoute,
  ShellSettingsAuditRoute: ShellSettingsAuditRoute,
  ShellSettingsMembersRoute: ShellSettingsMembersRoute,
  ShellSettingsModelsRoute: ShellSettingsModelsRoute,
  ShellSettingsProfileRoute: ShellSettingsProfileRoute,
  ShellSettingsSpendRoute: ShellSettingsSpendRoute,
  ShellSettingsIndexRoute: ShellSettingsIndexRoute,
}

const ShellSettingsRouteWithChildren = ShellSettingsRoute._addFileChildren(
  ShellSettingsRouteChildren,
)

interface ShellRouteChildren {
  ShellSplatRoute: typeof ShellSplatRoute
  ShellActivityRoute: typeof ShellActivityRoute
  ShellConnectionsRoute: typeof ShellConnectionsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellMembersRoute: typeof ShellMembersRoute
  ShellModelsRoute: typeof ShellModelsRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellOnboardingRoute: typeof ShellOnboardingRouteWithChildren
  ShellSettingsRoute: typeof ShellSettingsRouteWithChildren
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAppsAppRoute: typeof ShellAppsAppRoute
  ShellIntegrationsIntegrationRoute: typeof ShellIntegrationsIntegrationRoute
  ShellKnowledgeCollectionRoute: typeof ShellKnowledgeCollectionRoute
  ShellAppsIndexRoute: typeof ShellAppsIndexRoute
  ShellDomainsIndexRoute: typeof ShellDomainsIndexRoute
  ShellEnginesIndexRoute: typeof ShellEnginesIndexRoute
  ShellIntegrationsIndexRoute: typeof ShellIntegrationsIndexRoute
  ShellKnowledgeIndexRoute: typeof ShellKnowledgeIndexRoute
  ShellWorkflowsIndexRoute: typeof ShellWorkflowsIndexRoute
  ShellWorkflowsAppWorkflowRoute: typeof ShellWorkflowsAppWorkflowRoute
  ShellDomainsEngineIndexRoute: typeof ShellDomainsEngineIndexRoute
  ShellEnginesEngineIndexRoute: typeof ShellEnginesEngineIndexRoute
  ShellDomainsEngineAppsScreenRoute: typeof ShellDomainsEngineAppsScreenRoute
  ShellEnginesEngineAppsScreenRoute: typeof ShellEnginesEngineAppsScreenRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSplatRoute: ShellSplatRoute,
  ShellActivityRoute: ShellActivityRoute,
  ShellConnectionsRoute: ShellConnectionsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellMembersRoute: ShellMembersRoute,
  ShellModelsRoute: ShellModelsRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellOnboardingRoute: ShellOnboardingRouteWithChildren,
  ShellSettingsRoute: ShellSettingsRouteWithChildren,
  ShellIndexRoute: ShellIndexRoute,
  ShellAppsAppRoute: ShellAppsAppRoute,
  ShellIntegrationsIntegrationRoute: ShellIntegrationsIntegrationRoute,
  ShellKnowledgeCollectionRoute: ShellKnowledgeCollectionRoute,
  ShellAppsIndexRoute: ShellAppsIndexRoute,
  ShellDomainsIndexRoute: ShellDomainsIndexRoute,
  ShellEnginesIndexRoute: ShellEnginesIndexRoute,
  ShellIntegrationsIndexRoute: ShellIntegrationsIndexRoute,
  ShellKnowledgeIndexRoute: ShellKnowledgeIndexRoute,
  ShellWorkflowsIndexRoute: ShellWorkflowsIndexRoute,
  ShellWorkflowsAppWorkflowRoute: ShellWorkflowsAppWorkflowRoute,
  ShellDomainsEngineIndexRoute: ShellDomainsEngineIndexRoute,
  ShellEnginesEngineIndexRoute: ShellEnginesEngineIndexRoute,
  ShellDomainsEngineAppsScreenRoute: ShellDomainsEngineAppsScreenRoute,
  ShellEnginesEngineAppsScreenRoute: ShellEnginesEngineAppsScreenRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  GuestRoute: GuestRoute,
  KitRoute: KitRoute,
  SignInRoute: SignInRoute,
  DecisionsDecisionRoute: DecisionsDecisionRoute,
  KitComponentsNameRoute: KitComponentsNameRoute,
  KitExamplesNameRoute: KitExamplesNameRoute,
  AppsAppScreensScreenRoute: AppsAppScreensScreenRoute,
  DomainsEngineAppsScreenFullRoute: DomainsEngineAppsScreenFullRoute,
  EnginesEngineAppsScreenFullRoute: EnginesEngineAppsScreenFullRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
