/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --config=../connect/wrangler.jsonc --include-runtime=false` (hash: d1e343a7954d8779c712d1771c542637)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	AUDIT_ARCHIVE: R2Bucket;
	DB: D1Database;
	KNOWLEDGE: D1Database;
	EMAIL: SendEmail;
	LOADER: WorkerLoader;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	ROUTER_SECRET: string;
	BETTER_AUTH_SECRET: string;
	CAPABILITY_SIGNING_KEY: string;
	WORKSPACES: DurableObjectNamespace<import("./src/index").Workspace>;
	APPS: DurableObjectNamespace<import("./src/index").App>;
	AUDIT_LOG: DurableObjectNamespace<import("./src/index").AuditLog>;
	BUILTINS: DurableObjectNamespace<import("./src/index").Builtins>;
	ONBOARDING: DurableObjectNamespace<import("./src/index").Onboarding>;
	MODEL_LEDGER: DurableObjectNamespace<import("./src/index").ModelLedger>;
	CONNECT: Service<typeof import("../connect/src/index").default>;
	WORKFLOWS: Workflow<Parameters<import("./src/index").WorkflowDispatcher['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Workspace" | "App" | "AuditLog" | "Builtins" | "Onboarding" | "ModelLedger";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ROUTER_SECRET" | "BETTER_AUTH_SECRET" | "CAPABILITY_SIGNING_KEY">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.md" {
	const value: string;
	export default value;
}